---
title: "Mortality Diffs Plots and Tables"
author: "Eugenio Paglino"
output: html_document
---

```{r, echo=F, include=F}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.align = 'center'
)
```

```{r}
# Loading necessary packages
library(here)
library(patchwork)
library(gt)
library(tidyverse)
# Set seed for the Rmd
set.seed(42)
```

```{r, echo=FALSE, message=F, warning=F}
# Do not rely on this to completely clean your environment
# Better to do a full restart of R before running
rm(list=ls())

i_am('R/compWithWhitesPlots.Rmd')

inDir <- here('data','input')
outDir <- here('data','output')
figuresDir <- here('figures')
tablesDir <- here('tables')
```

```{r}
diff_trends_data <- function(data,thisSex) {
  
  diffData <- data %>%
    filter(majorCauses=='Total',
           sex==thisSex) %>%
    select(-logASDR) %>%
    group_by(sex,raceEthnicity,foreign,majorCauses,period) %>%
    summarise(ASDR = mean(ASDR)) %>%
    ungroup() %>%  
    pivot_wider(names_from = raceEthnicity,values_from = ASDR) %>%
    mutate(White = if_else(foreign=='Total',White,NA_real_),
           foreign = fct_relevel(foreign,'Total','US-Born','Foreign-Born')) %>%
    arrange(period,sex,foreign) %>%
    fill(White) %>%
    mutate(diffHispanic = Hispanic-White,
           diffBlack = Black-White,
           diffAsian = Asian-White) %>%
    select(-c(White:Asian)) %>%
    pivot_longer(diffHispanic:diffAsian,names_to = 'comparison',values_to = 'diff') %>%
    mutate(comparison = factor(case_when(comparison == 'diffHispanic' ~ 'Hispanic',
                                         comparison == 'diffBlack' ~ 'Black',
                                         comparison == 'diffAsian' ~ 'Asian'),
                               levels=c('Hispanic','Black','Asian')))
  
  return(diffData)
}
```

```{r}
diff_trends_plot <- function(data,thisSex) {

  linesData <- data %>%
    pivot_wider(names_from = period, values_from = diff)
  
  diffTrendsPlot <- data %>%
    ggplot() +
    geom_vline(xintercept = 1) +
    geom_segment(data = linesData,
                 mapping = aes(y=fct_relevel(foreign,'Total','US-Born','Foreign-Born'),
                               yend=fct_relevel(foreign,'Total','US-Born','Foreign-Born'),
                               x=`2017-2019`,xend=`2020`),
                 linewidth=0.3) +
    geom_point(mapping = aes(y=fct_relevel(foreign,'Total','US-Born','Foreign-Born'),
                             x=diff,shape=period,fill=period), size=3) +
    scale_shape_manual(values=c(22,21)) +
    scale_fill_manual(values=c('white','gray50')) +
    scale_x_continuous(limits = c(-800,800),breaks=seq(-750,750,250)) +
    labs(title=paste0(thisSex,'s'),
         x='',
         y='Diff of ASDRs (Ref. Total White Population)',
         shape='Period',
         fill='Period') +
    facet_wrap(~ comparison, nrow = 1) +
    theme_minimal() +
    theme(legend.position = 'bottom',
          panel.grid.major.y = element_blank(),
          panel.grid.minor = element_blank(),
          panel.spacing.y = unit(2,'lines'),
          strip.text.y.left = element_text(angle=0,size=13),
          strip.placement = 'outer',
          strip.background.x = element_rect(fill='white'))
  
  return(diffTrendsPlot)
}
```

```{r}
create_diff_trends_table <- function(dataMales,dataFemales) {
  
  data <- dataMales %>%
    add_row(dataFemales)
  
  data <- data %>%
    pivot_wider(names_from = c(period,sex), values_from = diff)
  
  summaryTable <- data %>%
    group_by(comparison) %>%
    select(comparison,
           foreign,
           `2017-2019_Male`,
           `2020_Male`,
           `2017-2019_Female`,
           `2020_Female`,
            ) %>%
    arrange(comparison) %>%
    gt() %>%
    cols_label(
      foreign = '',
      comparison = 'Race and Hispanic Origin',
      `2017-2019_Male` = '2017-2019',
      `2020_Male` = '2020',
      `2017-2019_Female` = '2017-2019',
      `2020_Female` = '2020') %>%
    fmt_number(
      columns = `2017-2019_Male`:`2020_Female`,
      decimals = 3
    ) %>%
    tab_spanner(
      label = 'Difference of ASDRs (Ref. Total White Population)',
      columns = `2017-2019_Male`:`2020_Female`,
      level = 2
    ) %>%
    tab_spanner(
      label = 'Males',
      columns = `2017-2019_Male`:`2020_Male`,
      level = 1
    ) %>%
    tab_spanner(
      label = 'Females',
      columns = `2017-2019_Female`:`2020_Female`,
      level = 1
    ) %>%
    tab_options(
      row_group.font.weight = 'bold'
    )
  
  return(summaryTable)
}
```

```{r}
ageStdRates <- read_csv(here(outDir,'ageStdRates.csv'))
ageStdRatesSens <- read_csv(here(outDir,'ageStdRatesSens.csv'))
```

## Race/Ethnicity ASDR Differences by Period, Sex, and Place of Birth

```{r}
diffTrendsMalesData <- diff_trends_data(ageStdRates,'Male')
diffTrendsFemalesData <- diff_trends_data(ageStdRates,'Female')
diffTrendsMalesPlot <- diff_trends_plot(diffTrendsMalesData,'Male')
diffTrendsFemalesPlot <- diff_trends_plot(diffTrendsFemalesData,'Female')
```

```{r}
diffTrendsMalesDataSens <- diff_trends_data(ageStdRatesSens,'Male')
diffTrendsFemalesDataSens <- diff_trends_data(ageStdRatesSens,'Female')
diffTrendsMalesPlotSens <- diff_trends_plot(diffTrendsMalesDataSens,'Male')
diffTrendsFemalesPlotSens <- diff_trends_plot(diffTrendsFemalesDataSens,'Female')
```

```{r, fig.width=8, fig.height=8}
combinedDiffPlots <- (diffTrendsFemalesPlot / diffTrendsMalesPlot) +
  plot_layout(guides='collect') +
  plot_annotation(tag_level = 'A') &
  theme(legend.position = 'bottom')

combinedDiffPlots
```

```{r}
svg(here(figuresDir,'diffTrendsPlot.svg'), width = 8, height = 8)
combinedDiffPlots
dev.off()
```

```{r, fig.width=8, fig.height=8}
combinedDiffPlotsSens <- (diffTrendsFemalesPlotSens / diffTrendsMalesPlotSens) +
  plot_layout(guides='collect') +
  plot_annotation(tag_level = 'A') &
  theme(legend.position = 'bottom')

combinedDiffPlotsSens
```

```{r}
svg(here(figuresDir,'diffTrendsPlotSens.svg'), width = 8, height = 8)
combinedDiffPlotsSens
dev.off()
```

```{r}
diffTrendsTable <- create_diff_trends_table(diffTrendsMalesData,diffTrendsFemalesData)
```

```{r}
gtsave(diffTrendsTable,here(figuresDir,'diffTrendsTable.docx'))
```
