---
title: "Cause-Specific Contributions to Mortality Differentials"
author: "Eugenio Paglino"
output: html_document
---

```{r, echo=F, include=F}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.align = 'center'
)
```

```{r}
# Loading necessary packages
library(here)
library(ggh4x)
library(patchwork)
library(gt)
library(tidyverse)
# Set seed for the Rmd
set.seed(42)
```

```{r, echo=FALSE, message=F, warning=F}
# Do not rely on this to completely clean your environment
# Better to do a full restart of R before running
rm(list=ls())

i_am('R/contributionsPlots.Rmd')

inDir <- here('data','input')
outDir <- here('data','output')
```

```{r}
create_contributions_data <- function(data) {
  contributionsData <- data %>%
    filter(foreign != 'Total') %>%
    select(-c(deaths,pop,logASDR,coefOfVar)) %>%
    pivot_wider(names_from = foreign, values_from = c(ASDR,ASDR.SD)) %>%
    rename(ASDRForeign = 'ASDR_Foreign-Born',
           ASDRUSBorn = 'ASDR_US-Born',
           ASDR.SDForeign = 'ASDR.SD_Foreign-Born',
           ASDR.SDUSBorn = 'ASDR.SD_US-Born') %>%
    mutate(ASDRDiff = ASDRForeign - ASDRUSBorn,
           ASDRDiff.SD = sqrt(ASDR.SDForeign^2+ASDR.SDUSBorn^2))
  
  return(contributionsData)
}
```

```{r}
create_diff_in_diff_data <- function(data) {

  diffInDiffData <- data %>% 
    pivot_wider(names_from = period, 
                values_from = c(ASDRForeign,ASDRUSBorn,ASDRDiff,
                                ASDR.SDForeign,ASDR.SDUSBorn,ASDRDiff.SD)) %>%
    mutate(ASDRDiffInDiff = (ASDRForeign_2020 - `ASDRForeign_2017-2019`) - (ASDRUSBorn_2020-`ASDRUSBorn_2017-2019`),
           ASDRDiffInDiff.SD = sqrt(`ASDR.SDForeign_2017-2019`^2 + 
                                    ASDR.SDForeign_2020^2 + 
                                    `ASDR.SDUSBorn_2017-2019`^2 + 
                                    ASDR.SDUSBorn_2020^2))
  
  return(diffInDiffData)
}
```

```{r}
redGrayPalette <- c(rgb(83/255,84/255,87/255),rgb(255/255,84/255,97/255))
```

```{r}
contributions_plot_color_safe <- function(data,thisSex) {
  contributionsPlot <- data %>%
    filter(majorCauses != 'Total',
           sex==thisSex) %>%
    ggplot() +
    geom_col(mapping=aes(y=majorCauses,
                         x=ASDRDiff,
                         fill=ASDRDiff>0),
             color='black',linewidth=0.1) +
    geom_linerange(mapping=aes(y=majorCauses,
                         xmin=ASDRDiff-ASDRDiff.SD*2,
                         xmax=ASDRDiff+ASDRDiff.SD*2),
             color='black',
             linewidth=1) +
    geom_vline(xintercept = 0) + 
    scale_fill_manual(values=redGrayPalette) + 
    coord_cartesian(xlim=c(-200,200)) +
    facet_nested_wrap(~period+fct_relevel(raceEthnicity,
                                  'White','Hispanic','Black','Asian'),
                 nrow=2) +
    labs(x='',
         y='',
         fill='',
         title='Cause-Specific Contributions to the Difference between Foreign-Born and US-Born ASDR') +
    theme_minimal() +
    theme(legend.position = 'bottom',
          panel.grid.major.y = element_blank(),
          panel.grid.minor.y = element_blank(),
          strip.text.x = element_text(angle=0),
          plot.title.position = "plot") +
    guides(fill='none')
  
  return(contributionsPlot)
}
```

```{r}
diff_in_diff_plot_color_safe <- function(data,thisSex) {
  diffInDiffPlot <- data %>%
    filter(majorCauses != 'Total',
           sex==thisSex) %>%
    ggplot() +
    geom_col(mapping=aes(y=majorCauses,
                         x=ASDRDiffInDiff,
                         fill=ASDRDiffInDiff>0),
             color='black',linewidth=0.1) +
      geom_linerange(mapping=aes(y=majorCauses,
                         xmin=ASDRDiffInDiff-ASDRDiffInDiff.SD*2,
                         xmax=ASDRDiffInDiff+ASDRDiffInDiff.SD*2),
             color='black',
             linewidth=1) +
    geom_vline(xintercept = 0) + 
    scale_fill_manual(values=redGrayPalette) + 
    coord_cartesian(xlim=c(-50,200)) +
    facet_wrap(~fct_relevel(raceEthnicity,
                                  'White','Hispanic','Black','Asian'),
               nrow = 1) +
    labs(x='',
         y='',
         fill='',
         title='Changes in the Cause-Specific Contributions to the Difference between Foreign-Born and US-Born ASDR (2020 - 2017-2019)') +
    theme_minimal() +
    theme(legend.position = 'bottom',
          panel.grid.major.y = element_blank(),
          panel.grid.minor.y = element_blank(),
          plot.title.position = "plot") +
    guides(fill='none')
  
  return(diffInDiffPlot)
}
```

```{r}
contributions_table <- function(data,thisSex) {
  contributionsTable <- data %>%
    filter(sex==thisSex) %>%
    mutate(raceEthnicity2 = if_else(majorCauses=='All other causes',raceEthnicity,'')) %>%
    select(raceEthnicity,
           raceEthnicity2,
           majorCauses,
      `ASDRUSBorn_2017-2019`,
      `ASDRForeign_2017-2019`,
      `ASDRDiff_2017-2019`,
      `ASDRUSBorn_2020`,
      `ASDRForeign_2020`,
      `ASDRDiff_2020`,
       ASDRDiffInDiff) %>%
    arrange(desc(raceEthnicity),majorCauses) %>%
    select(-raceEthnicity) %>%
    gt() %>%
    cols_label(
      raceEthnicity2 = '',
      majorCauses = 'Cause of Death',
      `ASDRUSBorn_2017-2019` = 'US-Born',
      `ASDRForeign_2017-2019` = 'Foreign-Born',
      `ASDRDiff_2017-2019` = 'Difference',
      `ASDRUSBorn_2020` = 'US-Born',
      `ASDRForeign_2020` = 'Foreign-Born',
      `ASDRDiff_2020` = 'Difference',
       ASDRDiffInDiff = 'Change in Difference') %>%
    fmt_number(
      columns = `ASDRUSBorn_2017-2019`:`ASDRDiffInDiff`,
      decimals = 1
    ) %>%
    tab_spanner(
      label = 'ASDR 2017-2019',
      columns = c(`ASDRUSBorn_2017-2019`,`ASDRForeign_2017-2019`,`ASDRDiff_2017-2019`)
    ) %>%
    tab_spanner(
      label = 'ASDR 2020',
      columns = c(`ASDRUSBorn_2020`,`ASDRForeign_2020`,`ASDRDiff_2020`)
    ) %>%
    tab_options(
      row_group.font.weight = 'bold'
    ) %>%
  cols_width(
    ASDRDiffInDiff ~ px(80)
  ) %>%
  tab_style(
    style = cell_text(weight = "bold",align = 'center'),
    locations = cells_body(columns = raceEthnicity2)
  )
}
```

```{r}
ageStdRates <- read_csv(here(outDir,'ageStdRates.csv'))
ageStdRatesSens <- read_csv(here(outDir,'ageStdRatesSens.csv'))
```

```{r}
contributionsData <- create_contributions_data(ageStdRates)
diffInDiffData <- create_diff_in_diff_data(contributionsData)

contributionsDataSens <- create_contributions_data(ageStdRatesSens)
diffInDiffDataSens <- create_diff_in_diff_data(contributionsDataSens)
```

```{r}
contributionsMalesColorrSafePlot <- contributions_plot_color_safe(contributionsData,'Male')
diffInDiffMalesColorrSafePlot <- diff_in_diff_plot_color_safe(diffInDiffData,'Male')

contributionsFemalesColorSafePlot <- contributions_plot_color_safe(contributionsData,'Female')
diffInDiffFemalesColorSafePlot <- diff_in_diff_plot_color_safe(diffInDiffData,'Female') 
```

```{r, fig.width=8, fig.height=9}
combinedPlotMalesColorSafe <- contributionsMalesColorrSafePlot/diffInDiffMalesColorrSafePlot + 
  plot_layout(heights=c(4, 2),guides = 'collect') +
  plot_annotation(tag_levels = 'A') &
  theme(legend.position = 'bottom')

combinedPlotMalesColorSafe
```

```{r}
svg(here('figures','USBornForeignDiffMalesColorSafePlot.svg'), width = 12, height = 10)
combinedPlotMalesColorSafe
dev.off()
```

```{r, fig.width=8, fig.height=12}
combinedPlotFemalesColorSafe <- contributionsFemalesColorSafePlot/diffInDiffFemalesColorSafePlot + 
  plot_layout(heights=c(4, 2),guides = 'collect') +
  plot_annotation(tag_levels = 'A') &
  theme(legend.position = 'bottom')
```

```{r}
svg(here('figures','USBornForeignDiffFemalesColorSafePlot.svg'), width = 12, height = 10)
combinedPlotFemalesColorSafe
dev.off()
```

```{r}
contributionsMalesColorrSafePlotSens <- contributions_plot_color_safe(contributionsDataSens,'Male')
diffInDiffMalesColorrSafePlotSens <- diff_in_diff_plot_color_safe(diffInDiffDataSens,'Male')

contributionsFemalesColorSafePlotSens <- contributions_plot_color_safe(contributionsDataSens,'Female')
diffInDiffFemalesColorSafePlotSens <- diff_in_diff_plot_color_safe(diffInDiffDataSens,'Female') 
```

```{r, fig.width=8, fig.height=9}
combinedPlotMalesColorSafeSens <- contributionsMalesColorrSafePlotSens/diffInDiffMalesColorrSafePlotSens + 
  plot_layout(heights=c(4, 2),guides = 'collect') +
  plot_annotation(tag_levels = 'A') &
  theme(legend.position = 'bottom')

combinedPlotMalesColorSafeSens
```

```{r}
svg(here('figures','USBornForeignDiffMalesColorSafePlotSens.svg'), width = 12, height = 10)
combinedPlotMalesColorSafeSens
dev.off()
```

```{r, fig.width=8, fig.height=12}
combinedPlotFemalesColorSafeSens <- contributionsFemalesColorSafePlotSens/diffInDiffFemalesColorSafePlotSens + 
  plot_layout(heights=c(4, 2),guides = 'collect') +
  plot_annotation(tag_levels = 'A') &
  theme(legend.position = 'bottom')
```

```{r}
svg(here('figures','USBornForeignDiffFemalesColorSafePlotSens.svg'), width = 12, height = 10)
combinedPlotFemalesColorSafeSens
dev.off()
```

```{r}
contributionsTableMales <- contributions_table(diffInDiffData,'Male')
contributionsTableFemales <- contributions_table(diffInDiffData,'Female')
```

```{r}
gtsave(contributionsTableMales,here('figures','contributionsTableMales.docx'))
gtsave(contributionsTableFemales,here('figures','contributionsTableFemales.docx'))
```