---
title: "Building Population Tables from CDC and ACS"
author: "Eugenio Paglino"
output: html_document
---

```{r, echo=F, include=F}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE
)
```

```{r}
# Loading necessary packages
library(here)
library(haven)
library(gt)
library(tidyverse)

# Set seed for the Rmd
set.seed(42)
```

```{r}
# Do not rely on this to completely clean your environment
# Better to do a full restart of R before running
rm(list=ls())

i_am('R/createPopTableCDC.Rmd')

inDir <- here('data','input')
outDir <- here('data','output')
```

```{r}
popData <- list.files(
  here(inDir,'CDCPopEstimates'),
  pattern = "*.txt",
  full.names = TRUE
  ) %>%
  map_dfr(
    ~ data.table::fread(
    .x,
    na.strings = c("Missing", "Suppressed", "Not Applicable"),
    keepLeadingZeros = TRUE,
    colClasses = list(character=8)
    ))

popData <- popData %>%
  mutate(Race = coalesce(Race, `Single Race 6`),
         `Race Code` = coalesce(`Race Code`,`Single Race 6 Code`))
```

```{r}
popData <- popData %>%
  select(year=`Year Code`,sex=Gender,race=Race,hispanic=`Hispanic Origin`,
         age=`Ten-Year Age Groups`,deaths=Deaths,pop=Population) %>%
  mutate(hispanic = factor(
    case_when(
      hispanic == 'Not Hispanic or Latino' ~ 1,
      hispanic == 'Hispanic or Latino' ~ 2,
      hispanic == 'Not Stated' ~ 3
      ),
    levels=1:3,
    labels=c('Non-Hispanic','Hispanic','Unknown')
    ),
         raceEthnicity = factor(
           case_when(
             hispanic == 'Hispanic' ~ 5,
             race == 'White' & hispanic == 'Non-Hispanic' ~ 1,
             race == 'Black or African American' & hispanic == 'Non-Hispanic' ~ 2,
             race == 'American Indian or Alaska Native' & hispanic == 'Non-Hispanic' ~ 3,
             race == 'Asian or Pacific Islander' & hispanic == 'Non-Hispanic' ~ 4,
             race == 'Asian' & hispanic == 'Non-Hispanic' ~ 4
             ),
           levels = 1:5,
           labels=c('White','Black',
                    'American Indian/Alaska Native',
                    'Asian',
                    'Hispanic')
           ),
    age = str_remove_all(age,'\\s'),
    age = str_remove_all(age,'year[s]?')) %>%
  select(-race)
```

```{r}
popData <- popData %>%
  filter(hispanic != 'Unknown',
         age != 'NotStated') %>%
  group_by(year,age,sex,raceEthnicity) %>%
  summarise(pop=sum(pop)) %>%
  ungroup()
```

```{r}
proportionsData <- arrow::read_feather(here(outDir,'proportionsData.feather'))
```

```{r}
popTable <- popData %>%
  left_join(proportionsData,by=c('year','age','sex','raceEthnicity')) %>%
  arrange(age,sex,raceEthnicity,year) %>%
  fill(propForeign:propUSBorn,.direction = 'down')
```

```{r}
popTable <- popTable %>%
  rename(popTotal = pop) %>%
  mutate(`popForeign-Born` = popTotal*(propForeign/100),
         `popUS-Born` = popTotal*(propUSBorn/100)) %>%
  pivot_longer(`popForeign-Born`:`popUS-Born`,
               names_to = 'foreign',values_to = 'pop',
               names_prefix = 'pop')
```

```{r}
popTable %>% arrow::write_feather(here(outDir,'popTable.feather'))
```

```{r}
popTable %>% 
  filter(!(age %in% c('<1','1-4','5-14','15-24'))) %>%
  group_by(age,sex,raceEthnicity,foreign) %>%
  summarise(pop=mean(pop)) %>%
  ungroup() %>%
  group_by(sex,raceEthnicity,foreign) %>%
  summarise(pop=sum(pop)) %>%
  ungroup() %>%
  mutate(pop = pop/1000000) %>%
  pivot_wider(values_from = pop,names_from = foreign)
```

```{r}
popTable %>% 
  filter(!(age %in% c('<1','1-4','5-14','15-24')),
         raceEthnicity %in% c('White','Black','Hispanic','Asian')) %>%
  group_by(age,sex,raceEthnicity,foreign) %>%
  summarise(pop=mean(pop)) %>%
  ungroup() %>%
  group_by(sex,raceEthnicity,foreign) %>%
  summarise(pop=sum(pop)) %>%
  ungroup() %>%
  mutate(pop = pop/1000000) %>%
  pivot_wider(values_from = pop,names_from = foreign) %>%
  mutate(pctForeign = 100*(`Foreign-Born`/(`Foreign-Born` + `US-Born`)),
         pctUSBorn = 100*(`US-Born`/(`Foreign-Born` + `US-Born`))) %>%
  group_by(sex) %>%
  gt() %>%
  cols_label(
    sex = 'Sex',
    raceEthnicity = 'Race/Ethnicity',
    `Foreign-Born` = 'Foreign-Born',
    `US-Born` = 'US-Born',
    `pctForeign` = 'Foreign-Born',
    `pctUSBorn` = 'US-Born') %>%
  fmt_number(
    columns = c(`Foreign-Born`,`US-Born`),
    sep_mark = ','
  ) %>%
  fmt_number(
    columns = c(pctForeign,pctUSBorn),
    decimals = 2
  ) %>%
  tab_spanner(
    label = 'Population 25+ Size (million)',
    columns = c(`Foreign-Born`,`US-Born`)
  ) %>%
  tab_spanner(
    label = 'Percentage',
    columns = c(pctForeign,pctUSBorn)
  ) %>%
  gt::gtsave(here('figures','popTable.png'),zoom=4)
```

