---
title: "Most Frequent Causes of Death Co-Occuring with COVID-19"
author: "Eugenio Paglino"
output:
  html_document
---

```{r, echo=F, include=F}

knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE
)

```

```{r}

# Loading necessary packages

library(here)
library(glue)
library(kableExtra)
library(tidyverse)
library(gt)

# Set seed for the Rmd
set.seed(42)
```

```{r}
# Do not rely on this to completely clean your environment
# Better to do a full restart of R before running

rm(list=ls())

i_am('R/createComorbTable.Rmd')

inDir <- here('data','input')
outDir <- here('data','output')
```

```{r}
comorbTable <- read_csv(here(outDir,'comorbTableUCD.csv'))
comorbTableComp <- read_csv(here(outDir,'comorbTableUCDComp.csv'))
```

```{r}
comorbTable <- comorbTable %>%
  left_join(comorbTableComp %>%
              select(majorCauses,raceEthnicity,foreign,casesComp=cases,propComp=prop),
            by=c('majorCauses','raceEthnicity','foreign')) %>%
  mutate(relativeFreq = prop/propComp)
```

```{r}
comorbTable %>%
  filter(foreign=='US-Born') %>%
  select(-foreign) %>%
  group_by(raceEthnicity) %>%
  gt() %>%
  cols_label(
    majorCauses='Cause of Death',
    cases='Number of Cases',
    casesComp='Number of Cases',
    prop='Frequency',
    propComp='Frequency', 
    relativeFreq='Ratio'
    ) %>%
  tab_spanner(
    label = '2020',
    columns = c(cases,prop)
  ) %>%
  tab_spanner(
    label = '2017-2019',
    columns = c(casesComp,propComp)
  ) %>%
  fmt_number(
    columns = c(prop,propComp,relativeFreq),
    decimals = 2
  ) %>%
  fmt_number(
    columns = c(cases,casesComp),
    decimals = 0
  ) %>%
  gtsave(here('figures','relativeComorbTableUS.png'),
         vheight=2000,vwidth=1000,zoom=4)
```

```{r}
comorbTable %>%
  filter(foreign=='Foreign-Born') %>%
  select(-foreign) %>%
  group_by(raceEthnicity) %>%
  gt() %>%
  cols_label(
    majorCauses='Cause of Death',
    cases='Number of Cases',
    casesComp='Number of Cases',
    prop='Frequency',
    propComp='Frequency', 
    relativeFreq='Ratio'
    ) %>%
  tab_spanner(
    label = '2020',
    columns = c(cases,prop)
  ) %>%
  tab_spanner(
    label = '2017-2019',
    columns = c(casesComp,propComp)
  ) %>%
  fmt_number(
    columns = c(prop,propComp,relativeFreq),
    decimals = 2
  ) %>%
  fmt_number(
    columns = c(cases,casesComp),
    decimals = 0
  ) %>%
  gtsave(here('figures','relativeComorbTableForeign.png'),
       vwidth = 1000,vheight = 2000,zoom=4)
```

```{r}
comorbTable %>%
  write_csv(here(outDir,'relativeComorbTable.csv'))
```


